version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  # 追記
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  # 追記
  db:
    image: mysql:5.7
    build: ./infra/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel_local
      MYSQL_USER: phper
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      TZ: "Asia/Tokyo"
    volumes:
      - db-store:/var/lib/mysql

  # phpMyadominのコンテナ作成      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db #mysqlサービス名を指定
      - PMA_USER=phper
      - PMA_PASSWORD=secret
    links:
      - db
    ports:
      - 4040:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions

volumes:
  db-store: